#!/bin/sh

: ${CC:="gcc"}
: ${STRIP:="strip"}
: ${CFLAGS:="-pipe -Os -fno-ident -fomit-frame-pointer -fno-stack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables"}
: ${CPPFLAGS:="-DNDEBUG -U_FORTIFY_SOURCE"}
: ${LDFLAGS:="-Wl,--strip-all"}
: ${LDLIBS:=""}
: ${WARNINGS:="-Wdouble-promotion -Wpointer-arith"}

mkdir bin 2>/dev/null

$CC -std=c99 $CPPFLAGS $CFLAGS $WARNINGS init.c     -o bin/init     $LDFLAGS $LDLIBS
$CC -std=c99 $CPPFLAGS $CFLAGS $WARNINGS reboot.c   -o bin/reboot   $LDFLAGS $LDLIBS
$CC -std=c99 $CPPFLAGS $CFLAGS $WARNINGS shutdown.c -o bin/shutdown $LDFLAGS $LDLIBS

$STRIP -R .note.ABI-tag -R .gnu.version -R .eh_frame_hdr -R .eh_frame bin/init
$STRIP -R .note.ABI-tag -R .gnu.version -R .eh_frame_hdr -R .eh_frame bin/reboot
$STRIP -R .note.ABI-tag -R .gnu.version -R .eh_frame_hdr -R .eh_frame bin/shutdown
